'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MarioBros.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1000pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1000pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _100pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_100pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1upMushroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1upMushroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1upMushroomDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1upMushroomDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1upMushroomSelector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1upMushroomSelector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2000pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2000pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _200pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_200pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4000pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4000pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _400pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_400pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5000pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5000pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _500pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_500pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8000pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8000pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _800pts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_800pts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AfterBowserDead8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterBowserDead8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Axe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Axe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bloober() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bloober", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bowser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bowser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BrickBlockBrown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrickBlockBrown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BrickBlockCastle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrickBlockCastle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BrickBlockDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrickBlockDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BulletBill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BulletBill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BulletBillGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BulletBillGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuzzyBeetle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuzzyBeetle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuzzyBeetleDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuzzyBeetleDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuzzyBeetleGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuzzyBeetleGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuzzyBeetleShell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuzzyBeetleShell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuzzyBeetleShellDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuzzyBeetleShellDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuzzyBeetleShellGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuzzyBeetleShellGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cannon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cannon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CannonLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CannonLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CannonSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CannonSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CheepCheepGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheepCheepGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CheepCheepRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheepCheepRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CoinForBlackBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CoinForBlackBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CoinForBlueBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CoinForBlueBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CoinForWater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CoinForWater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmptyBlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmptyBlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmptyBlockCastle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmptyBlockCastle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmptyBlockDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmptyBlockDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmptyBlockGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmptyBlockGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMarioCrouching() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMarioCrouching", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMarioJumping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMarioJumping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMarioJumpingLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMarioJumpingLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMarioLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMarioLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMarioSkidding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMarioSkidding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMarioStanding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMarioStanding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FieryMarioStandingLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieryMarioStandingLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FireBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FireBall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FireBallHit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FireBallHit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FireFlower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FireFlower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FlagFromPole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FlagFromPole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FlagFromPolePink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FlagFromPolePink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HammerGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HammerGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InvincibleFieryMario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvincibleFieryMario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaParatroopaGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaParatroopaGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaParatroopaGreenDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaParatroopaGreenDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaParatroopaRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaParatroopaRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaTroopaGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaTroopaGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaTroopaGreenDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaTroopaGreenDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaTroopaRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaTroopaRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaTroopaShellGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaTroopaShellGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaTroopaShellGreenDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaTroopaShellGreenDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KoopaTroopaShellRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KoopaTroopaShellRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lakitu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lakitu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property level_1_noblocks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level_1_noblocks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LittleGoomba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LittleGoomba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LittleGoombaDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LittleGoombaDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LittleGoombaGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LittleGoombaGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Luigi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Luigi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuigiJumping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuigiJumping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuigiSkidding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuigiSkidding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuigiStanding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuigiStanding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MagicMushroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MagicMushroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MagicMushroomSelector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MagicMushroomSelector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarioJumping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarioJumping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarioJumpingLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarioJumpingLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarioLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarioLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarioSkidding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarioSkidding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarioStanding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarioStanding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarioStandingLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarioStandingLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MedPipe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MedPipe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_dialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_dialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MushroomRetainer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MushroomRetainer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property options_dialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("options_dialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pipe_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pipe_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pipe_med() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pipe_med", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pipe_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pipe_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PiranaPlant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PiranaPlant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PiranaPlantDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PiranaPlantDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Podoboo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Podoboo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Princess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Princess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuestionBlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionBlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuestionBlockCastle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionBlockCastle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuestionBlockDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionBlockDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmallPipe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallPipe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property space_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("space_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SpinningFireBalls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpinningFireBalls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spiny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spiny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SpinysEggs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpinysEggs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StairsBlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StairsBlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Starman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Starman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperLuigi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperLuigi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperLuigiCrouching() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperLuigiCrouching", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperLuigiJumping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperLuigiJumping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperLuigiSkidding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperLuigiSkidding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperLuigiStanding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperLuigiStanding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supermariobrosbackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supermariobrosbackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMarioCrouching() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMarioCrouching", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMarioJumping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMarioJumping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMarioJumpingLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMarioJumpingLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMarioLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMarioLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMarioSkidding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMarioSkidding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMarioStanding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMarioStanding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuperMarioStandingLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuperMarioStandingLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheHammerBrothers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheHammerBrothers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheHammerBrothersDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheHammerBrothersDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheHammerBrothersWithHammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheHammerBrothersWithHammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
